_target_: models.pl_models.gnn.WyckoffGNN

num_gnn_layers: 3
hidden_dim: 256
dof_pos_sg_emb_size: 128
gnn_activation: SiLU
composition_encoder_dim: 256
composition_film: true
no_multiplicity_encoding: false
binary_dof_encoding: false
no_softmax: false
mlp_hidden_layers: 3
mlp_activation: SiLU
