defaults:
  - decoder: wyckoff_gnn
  - _self_

_target_: models.pl_models.flow.DiscreteFlowModule

num_elements: ${data.num_elements}
max_num_atoms: 54
flow_source: zeros
zero_df_loss_weight: 1.0
inf_df_loss_weight: 1.0
conditional_composition: true

validation_seed: ${seed}
