_target_: models.pl_models.space_group.SpaceGroupModule

num_elements: ${data.num_elements}
max_num_atoms: 54
hidden_dim: 256
composition_encoder_dim: 256
compatibility: true
mlp_hidden_layers: 3
mlp_activation: SiLU
# Hidden activations in the classification and compatibility MLPs.
dropout: 0.0
